-- Complete Sample Data for Arbeit Database
-- This script contains sample data for ALL tables
-- Run this AFTER the Spring Boot application has started and created the tables

USE arbeit;

-- Disable foreign key checks temporarily
SET FOREIGN_KEY_CHECKS = 0;

-- Clear existing data (optional - remove if you want to keep existing data)
-- TRUNCATE TABLE applications;
-- TRUNCATE TABLE jobs;
-- TRUNCATE TABLE users;
-- TRUNCATE TABLE companies;

-- ===============================
-- 1. COMPANIES TABLE DATA
-- ===============================
INSERT INTO companies (id, bid, name, email, company_email, company_name, address, city, state, country, zip_code, phone, website, industry, company_size, description, mission, vision, password, role, verified, email_verified, email_verification_token, email_verification_expiry, created_at, updated_at) VALUES
(1, 'B001', 'John Smith', 'john.smith@techcorp.com', 'hr@techcorp.com', 'TechCorp Solutions', '123 Business Street', 'San Francisco', 'CA', 'USA', '94105', '+1-555-0101', 'https://techcorp.com', 'Technology', '51-200', 'Leading technology solutions provider specializing in enterprise software', 'To innovate and deliver cutting-edge technology solutions', 'To be the global leader in enterprise software solutions', '$2a$10$encryptedpassword1', 'business', true, true, NULL, NULL, NOW(), NOW()),

(2, 'B002', 'Sarah Johnson', 'sarah.j@innovatetech.com', 'careers@innovatetech.com', 'InnovateTech', '456 Innovation Avenue', 'Austin', 'TX', 'USA', '73301', '+1-555-0102', 'https://innovatetech.com', 'Software Development', '11-50', 'Innovative software development company focused on modern solutions', 'To create innovative software solutions that transform businesses', 'To revolutionize software development industry', '$2a$10$encryptedpassword2', 'business', true, true, NULL, NULL, NOW(), NOW()),

(3, 'B003', 'Mike Davis', 'mike.d@startupco.com', 'jobs@startupco.com', 'StartupCo', '789 Startup Boulevard', 'New York', 'NY', 'USA', '10001', '+1-555-0103', 'https://startupco.com', 'FinTech', '1-10', 'Early-stage FinTech startup disrupting traditional banking', 'To democratize financial services through technology', 'To make financial services accessible to everyone worldwide', '$2a$10$encryptedpassword3', 'business', true, true, NULL, NULL, NOW(), NOW()),

(4, 'B004', 'Emily Chen', 'emily.chen@globaltech.com', 'talent@globaltech.com', 'GlobalTech Corp', '321 Tech Plaza', 'Seattle', 'WA', 'USA', '98101', '+1-555-0104', 'https://globaltech.com', 'Information Technology', '201-500', 'Global technology corporation providing comprehensive IT solutions', 'To provide world-class technology solutions globally', 'To be the most trusted technology partner worldwide', '$2a$10$encryptedpassword4', 'business', true, true, NULL, NULL, NOW(), NOW()),

(5, 'B005', 'David Rodriguez', 'david.r@medtech.com', 'careers@medtech.com', 'MedTech Innovations', '654 Health Street', 'Boston', 'MA', 'USA', '02101', '+1-555-0105', 'https://medtech.com', 'Healthcare Technology', '51-200', 'Healthcare technology company improving patient outcomes', 'To improve healthcare through innovative technology', 'To revolutionize healthcare delivery globally', '$2a$10$encryptedpassword5', 'business', true, true, NULL, NULL, NOW(), NOW());

-- ===============================
-- 2. USERS TABLE DATA
-- ===============================
INSERT INTO users (id, user_id, email, password, first_name, last_name, phone, address, city, state, country, zip_code, role, current_job_title, current_company, experience, skills, education, linkedin_url, github_url, portfolio_url, resume_file_name, resume_file_id, email_verified, email_verification_token, email_verification_expiry, created_at, updated_at) VALUES
(1, '123', 'alice.developer@email.com', '$2a$10$encryptedpassword6', 'Alice', 'Johnson', '+1-555-0201', '123 Main Street', 'Seattle', 'WA', 'USA', '98101', 'user', 'Senior Software Engineer', 'TechCorp Solutions', '5-7 years', 'Java,Spring Boot,React,Node.js,Docker,Kubernetes,AWS,Microservices', 'Bachelor of Computer Science', 'https://linkedin.com/in/alicejohnson', 'https://github.com/alicejohnson', 'https://alicejohnson.dev', '123_resume.pdf', '123_resume.pdf', true, NULL, NULL, NOW(), NOW()),

(2, '456', 'bob.manager@email.com', '$2a$10$encryptedpassword7', 'Bob', 'Smith', '+1-555-0202', '456 Oak Avenue', 'Chicago', 'IL', 'USA', '60601', 'user', 'Product Manager', 'InnovateTech', '7-10 years', 'Product Management,Agile,Scrum,SQL,Analytics,User Research,Data Analysis', 'MBA', 'https://linkedin.com/in/bobsmith', NULL, NULL, '456_resume.pdf', '456_resume.pdf', true, NULL, NULL, NOW(), NOW()),

(3, '789', 'carol.designer@email.com', '$2a$10$encryptedpassword8', 'Carol', 'Williams', '+1-555-0203', '789 Pine Street', 'Boston', 'MA', 'USA', '02101', 'user', 'UX Designer', 'StartupCo', '3-5 years', 'UI/UX Design,Figma,Adobe XD,Sketch,User Research,Prototyping,Design Systems', 'Bachelor of Fine Arts', 'https://linkedin.com/in/carolwilliams', NULL, 'https://carolwilliams.design', '789_resume.pdf', '789_resume.pdf', true, NULL, NULL, NOW(), NOW()),

(4, '234', 'david.analyst@email.com', '$2a$10$encryptedpassword9', 'David', 'Brown', '+1-555-0204', '321 Elm Street', 'Denver', 'CO', 'USA', '80201', 'user', 'Data Analyst', 'TechCorp Solutions', '2-3 years', 'Python,SQL,Tableau,Excel,Statistics,R,Power BI,Machine Learning', 'Bachelor of Statistics', 'https://linkedin.com/in/davidbrown', 'https://github.com/davidbrown', NULL, '234_resume.pdf', '234_resume.pdf', true, NULL, NULL, NOW(), NOW()),

(5, '567', 'eve.engineer@email.com', '$2a$10$encryptedpassword10', 'Eve', 'Davis', '+1-555-0205', '654 Maple Avenue', 'Portland', 'OR', 'USA', '97201', 'user', 'DevOps Engineer', 'InnovateTech', '4-6 years', 'AWS,Docker,Kubernetes,Jenkins,GitLab CI,Python,Terraform,Monitoring', 'Bachelor of Computer Engineering', 'https://linkedin.com/in/evedavis', 'https://github.com/evedavis', NULL, '567_resume.pdf', '567_resume.pdf', true, NULL, NULL, NOW(), NOW()),

(6, '890', 'frank.marketing@email.com', '$2a$10$encryptedpassword11', 'Frank', 'Miller', '+1-555-0206', '987 Cedar Lane', 'Miami', 'FL', '33101', 'user', 'Marketing Specialist', 'GlobalTech Corp', '3-5 years', 'Digital Marketing,SEO,Social Media,Google Analytics,Content Marketing,Email Marketing', 'Bachelor of Marketing', 'https://linkedin.com/in/frankmiller', NULL, 'https://frankmiller.marketing', '890_resume.pdf', '890_resume.pdf', true, NULL, NULL, NOW(), NOW()),

(7, '321', 'grace.sales@email.com', '$2a$10$encryptedpassword12', 'Grace', 'Wilson', '+1-555-0207', '147 Birch Road', 'Phoenix', 'AZ', '85001', 'user', 'Sales Representative', 'StartupCo', '6-8 years', 'Sales,Salesforce,CRM,Negotiation,Customer Relationship,Lead Generation', 'Bachelor of Business Administration', 'https://linkedin.com/in/gracewilson', NULL, NULL, '321_resume.pdf', '321_resume.pdf', true, NULL, NULL, NOW(), NOW()),

(8, '654', 'henry.hr@email.com', '$2a$10$encryptedpassword13', 'Henry', 'Taylor', '+1-555-0208', '258 Spruce Street', 'Atlanta', 'GA', '30301', 'user', 'HR Manager', 'MedTech Innovations', '8-10 years', 'Human Resources,Talent Acquisition,Employee Relations,HR Policies,Recruiting', 'Master of Human Resources', 'https://linkedin.com/in/henrytaylor', NULL, NULL, '654_resume.pdf', '654_resume.pdf', true, NULL, NULL, NOW(), NOW()),

(9, '987', 'ivy.qa@email.com', '$2a$10$encryptedpassword14', 'Ivy', 'Anderson', '+1-555-0209', '369 Willow Avenue', 'Salt Lake City', 'UT', '84101', 'user', 'QA Engineer', 'GlobalTech Corp', '4-6 years', 'Quality Assurance,Test Automation,Selenium,JUnit,API Testing,Manual Testing', 'Bachelor of Computer Science', 'https://linkedin.com/in/ivyanderson', 'https://github.com/ivyanderson', NULL, '987_resume.pdf', '987_resume.pdf', true, NULL, NULL, NOW(), NOW()),

(10, '135', 'jack.frontend@email.com', '$2a$10$encryptedpassword15', 'Jack', 'Thomas', '+1-555-0210', '741 Poplar Drive', 'Nashville', 'TN', '37201', 'user', 'Frontend Developer', 'InnovateTech', '2-3 years', 'JavaScript,React,TypeScript,HTML5,CSS3,Vue.js,Webpack', 'Bachelor of Computer Science', 'https://linkedin.com/in/jackthomas', 'https://github.com/jackthomas', 'https://jackthomas.dev', '135_resume.pdf', '135_resume.pdf', true, NULL, NULL, NOW(), NOW());

-- ===============================
-- 3. JOBS TABLE DATA
-- ===============================
INSERT INTO jobs (id, job_id, title, company_name, business_name, company_email, bid, location, city, state, country, remote_work, job_type, department, description, requirements, benefits, qualification, skills_required, salary_min, salary_max, salary_currency, hide_salary, screening_questions, hiring_process, application_instructions, status, applicants, posted_date, updated_date, closing_date) VALUES
(1, 'J000001', 'Senior Java Developer', 'TechCorp Solutions', 'TechCorp Solutions', 'hr@techcorp.com', 'B001', 'San Francisco, CA', 'San Francisco', 'CA', 'USA', true, 'Full-time', 'Engineering', 'We are looking for an experienced Java developer to join our team and work on cutting-edge enterprise applications. You will be working on microservices architecture and cloud-native solutions.', '5+ years of Java development experience, Spring Boot proficiency, Microservices experience, Docker and Kubernetes knowledge', 'Health insurance, 401k matching, Flexible work hours, Remote work options, Professional development budget, Stock options', 'Bachelor degree in Computer Science or related field', 'Java,Spring Boot,Microservices,Docker,AWS,Kubernetes', 120000.00, 160000.00, 'USD', false, '["What is your experience with Spring Boot?","Describe a microservices project you worked on","How do you handle database migrations?"]', 'Application Review -> Technical Interview -> System Design Interview -> Final Interview -> Offer', 'Please include your GitHub profile and links to projects you have worked on', 'Active', 3, DATE_SUB(NOW(), INTERVAL 7 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY)),

(2, 'J000002', 'Product Manager', 'InnovateTech', 'InnovateTech', 'careers@innovatetech.com', 'B002', 'Austin, TX', 'Austin', 'TX', 'USA', false, 'Full-time', 'Product', 'Join our product team to drive product strategy and development for our innovative software solutions. You will work closely with engineering and design teams.', '3+ years product management experience, Experience with Agile methodologies, Technical background preferred, Strong analytical and communication skills', 'Competitive salary, Stock options, Health benefits, Learning budget, Flexible PTO, Remote work Fridays', 'Bachelor degree required, MBA preferred', 'Product Management,Agile,Scrum,SQL,Analytics,User Research', 90000.00, 130000.00, 'USD', false, '["What product have you launched?","How do you prioritize features?","Describe your experience with Agile"]', 'Resume Review -> Product Case Study -> Leadership Interview -> Final Interview -> Offer', 'Include links to products you have launched and your product portfolio', 'Active', 2, DATE_SUB(NOW(), INTERVAL 5 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 25 DAY)),

(3, 'J000003', 'UX Designer', 'StartupCo', 'StartupCo', 'jobs@startupco.com', 'B003', 'New York, NY', 'New York', 'NY', 'USA', true, 'Full-time', 'Design', 'We are seeking a talented UX Designer to create intuitive and beautiful user experiences for our FinTech platform. You will work on user research, prototyping, and design systems.', '3+ years UX design experience, Proficiency in Figma and design systems, Portfolio required, Experience with user research and usability testing', 'Equity package, Health insurance, Flexible hours, Co-working space, Design conference budget, Learning stipend', 'Bachelor in Design or related field', 'UI/UX Design,Figma,Sketch,User Research,Prototyping,Design Systems,Adobe Creative Suite', 70000.00, 100000.00, 'USD', false, '["Show us your design process","What is your favorite design tool?","How do you conduct user research?"]', 'Portfolio Review -> Design Challenge -> Team Interview -> Culture Fit Interview -> Offer', 'Please include your portfolio link and design case studies. Prepare to discuss your design process.', 'Active', 1, DATE_SUB(NOW(), INTERVAL 3 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 20 DAY)),

(4, 'J000004', 'Data Analyst', 'TechCorp Solutions', 'TechCorp Solutions', 'hr@techcorp.com', 'B001', 'Remote', 'San Francisco', 'CA', 'USA', true, 'Full-time', 'Analytics', 'Looking for a data analyst to help us make data-driven decisions and create insightful dashboards. You will work with large datasets and create visualizations for executive reporting.', '2+ years data analysis experience, SQL proficiency, Experience with BI tools like Tableau or Power BI, Python or R knowledge', 'Remote work, Learning opportunities, Health benefits, Flexible schedule, Professional development, Home office stipend', 'Bachelor in Mathematics, Statistics, or related field', 'SQL,Python,Tableau,Excel,Statistics,R,Power BI,Machine Learning', 65000.00, 85000.00, 'USD', false, '["What SQL queries have you written?","Experience with data visualization?","How do you approach data cleaning?"]', 'Technical Assessment -> Data Analysis Interview -> Presentation Interview -> Final Interview', 'Include SQL queries you have written and links to dashboards you have created', 'Active', 4, DATE_SUB(NOW(), INTERVAL 10 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 35 DAY)),

(5, 'J000005', 'DevOps Engineer', 'InnovateTech', 'InnovateTech', 'careers@innovatetech.com', 'B002', 'Austin, TX', 'Austin', 'TX', 'USA', false, 'Full-time', 'Engineering', 'We need a DevOps engineer to help us build and maintain our cloud infrastructure and CI/CD pipelines. You will work with AWS and container orchestration technologies.', '4+ years DevOps/Infrastructure experience, AWS/Azure experience, Container orchestration knowledge, CI/CD pipeline experience', 'Competitive salary, Cloud certifications paid, Flexible work, Learning budget, Conference attendance, Remote work options', 'Bachelor in Computer Science or related field', 'AWS,Docker,Kubernetes,Jenkins,GitLab CI,Python,Terraform,Monitoring', 95000.00, 125000.00, 'USD', false, '["What cloud platforms have you worked with?","Experience with Kubernetes?","How do you approach infrastructure as code?"]', 'Technical Interview -> Infrastructure Design -> Team Fit Interview -> Leadership Interview', 'Include links to infrastructure projects and your GitHub repositories', 'Active', 2, DATE_SUB(NOW(), INTERVAL 8 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 28 DAY)),

(6, 'J000006', 'Frontend Developer', 'GlobalTech Corp', 'GlobalTech Corp', 'talent@globaltech.com', 'B004', 'Seattle, WA', 'Seattle', 'WA', 'USA', true, 'Full-time', 'Engineering', 'Join our frontend team to build modern web applications using React and TypeScript. You will work on user-facing features and collaborate with designers and backend developers.', '2+ years frontend development experience, React and TypeScript proficiency, Experience with modern CSS frameworks, Git knowledge', 'Comprehensive health benefits, 401k with matching, Flexible work arrangements, Professional development budget, Stock purchase plan', 'Bachelor in Computer Science or related field', 'JavaScript,React,TypeScript,HTML5,CSS3,Vue.js,Webpack,Redux', 80000.00, 110000.00, 'USD', false, '["What React projects have you built?","How do you optimize React applications?","Experience with TypeScript?"]', 'Code Challenge -> Technical Interview -> Team Interview -> Final Interview -> Offer', 'Include your GitHub profile and links to projects. Be prepared for a coding challenge.', 'Active', 3, DATE_SUB(NOW(), INTERVAL 12 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 40 DAY)),

(7, 'J000007', 'Marketing Specialist', 'GlobalTech Corp', 'GlobalTech Corp', 'talent@globaltech.com', 'B004', 'Remote', 'Seattle', 'WA', 'USA', true, 'Full-time', 'Marketing', 'We are looking for a marketing specialist to develop and execute digital marketing campaigns. You will manage social media, content marketing, and SEO initiatives.', '3+ years digital marketing experience, SEO and SEM knowledge, Social media expertise, Analytics proficiency, Content creation skills', 'Remote work, Health benefits, Flexible hours, Marketing budget, Professional development, Conference attendance', 'Bachelor in Marketing, Communications, or related field', 'Digital Marketing,SEO,Social Media,Google Analytics,Content Marketing,Email Marketing,Facebook Ads', 55000.00, 75000.00, 'USD', false, '["What marketing campaigns have you run?","How do you measure marketing ROI?","Experience with Google Ads?"]', 'Portfolio Review -> Marketing Strategy Interview -> Creative Interview -> Final Interview', 'Include links to marketing campaigns you have created and analytics dashboards', 'Active', 1, DATE_SUB(NOW(), INTERVAL 6 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 22 DAY)),

(8, 'J000008', 'Sales Representative', 'StartupCo', 'StartupCo', 'jobs@startupco.com', 'B003', 'New York, NY', 'New York', 'NY', 'USA', false, 'Full-time', 'Sales', 'Join our sales team to drive revenue growth for our FinTech platform. You will identify and close deals with enterprise clients and startups.', '2+ years sales experience, SaaS sales experience preferred, Strong communication and negotiation skills, CRM experience', 'Base salary + commission, Health insurance, Flexible hours, Sales training, Career advancement opportunities', 'Bachelor degree preferred', 'Sales,Salesforce,CRM,Negotiation,Customer Relationship,Lead Generation,Presentation Skills', 60000.00, 100000.00, 'USD', false, '["What is your sales process?","How do you handle objections?","Experience with enterprise sales?"]', 'Resume Review -> Sales Role Play -> Leadership Interview -> Final Interview -> Offer', 'Include your sales achievements and commission history', 'Active', 2, DATE_SUB(NOW(), INTERVAL 9 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 32 DAY)),

(9, 'J000009', 'HR Manager', 'MedTech Innovations', 'MedTech Innovations', 'careers@medtech.com', 'B005', 'Boston, MA', 'Boston', 'MA', 'USA', true, 'Full-time', 'Human Resources', 'We are seeking an experienced HR Manager to lead our people operations. You will manage recruitment, employee relations, and HR policies for our growing healthcare technology company.', '5+ years HR experience, Recruitment expertise, Employee relations experience, HR policy development, Healthcare industry experience preferred', 'Comprehensive benefits, Flexible work, Professional development, Leadership training, Conference attendance', 'Bachelor degree required, Master degree in HR preferred', 'Human Resources,Talent Acquisition,Employee Relations,HR Policies,Recruiting,Performance Management', 85000.00, 115000.00, 'USD', false, '["How do you approach talent acquisition?","Experience with employee relations?","How do you handle HR compliance?"]', 'Resume Review -> HR Assessment -> Leadership Interview -> Culture Fit Interview -> Offer', 'Include examples of HR policies you have developed and recruitment strategies you have implemented', 'Active', 1, DATE_SUB(NOW(), INTERVAL 11 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 38 DAY)),

(10, 'J000010', 'QA Engineer', 'GlobalTech Corp', 'GlobalTech Corp', 'talent@globaltech.com', 'B004', 'Seattle, WA', 'Seattle', 'WA', 'USA', true, 'Full-time', 'Quality Assurance', 'Join our QA team to ensure the quality and reliability of our software products. You will create automated tests, perform manual testing, and work closely with developers.', '3+ years QA experience, Test automation experience, Selenium or similar tools, API testing experience, Manual testing skills', 'Health benefits, Flexible work, Learning budget, Certification reimbursement, Professional development', 'Bachelor in Computer Science or related field', 'Quality Assurance,Test Automation,Selenium,JUnit,API Testing,Manual Testing,Postman', 70000.00, 95000.00, 'USD', false, '["What testing frameworks have you used?","How do you approach test automation?","Experience with API testing?"]', 'Technical Assessment -> QA Interview -> Team Interview -> Final Interview -> Offer', 'Include examples of test cases you have written and automation frameworks you have built', 'Active', 2, DATE_SUB(NOW(), INTERVAL 4 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 18 DAY));

-- ===============================
-- 4. APPLICATIONS TABLE DATA
-- ===============================
INSERT INTO applications (id, user_id, job_id, full_name, email, phone, cover_letter, status, resume_file_name, resume_id, experience, current_company, current_job_title, education, linkedin_url, portfolio_url, applied_date, updated_date, reviewed_date, reviewer_notes, rating) VALUES
(1, '123', 'J000001', 'Alice Johnson', 'alice.developer@email.com', '+1-555-0201', 'I am excited to apply for the Senior Java Developer position at TechCorp Solutions. With 6 years of experience in Java development and Spring Boot, I believe I would be a great fit for your team. I have extensive experience with microservices architecture and cloud-native applications.', 'Under Review', '123_resume.pdf', '123_resume.pdf', '5-7 years', 'TechCorp Solutions', 'Senior Software Engineer', 'Bachelor of Computer Science', 'https://linkedin.com/in/alicejohnson', 'https://alicejohnson.dev', DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'Strong technical background, good fit for the role. Impressed with Spring Boot experience.', 4),

(2, '456', 'J000002', 'Bob Smith', 'bob.manager@email.com', '+1-555-0202', 'I am interested in the Product Manager position at InnovateTech. My 8 years of product management experience and technical background make me well-suited for this role. I have successfully launched multiple products and led cross-functional teams.', 'Pending', '456_resume.pdf', '456_resume.pdf', '7-10 years', 'InnovateTech', 'Product Manager', 'MBA', 'https://linkedin.com/in/bobsmith', NULL, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), NULL, NULL, NULL),

(3, '789', 'J000003', 'Carol Williams', 'carol.designer@email.com', '+1-555-0203', 'I would love to bring my UX design expertise to StartupCo. My portfolio demonstrates my ability to create user-centered designs that drive business results. I am passionate about solving complex user problems through design thinking.', 'Shortlisted', '789_resume.pdf', '789_resume.pdf', '3-5 years', 'StartupCo', 'UX Designer', 'Bachelor of Fine Arts', 'https://linkedin.com/in/carolwilliams', 'https://carolwilliams.design', DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 'Excellent portfolio, strong design skills. Great fit for our FinTech platform design needs.', 5),

(4, '234', 'J000004', 'David Brown', 'david.analyst@email.com', '+1-555-0204', 'I am applying for the Data Analyst position at TechCorp Solutions. My background in statistics and experience with SQL and Tableau would allow me to contribute immediately. I enjoy turning complex data into actionable insights.', 'Accepted', '234_resume.pdf', '234_resume.pdf', '2-3 years', 'TechCorp Solutions', 'Data Analyst', 'Bachelor of Statistics', 'https://linkedin.com/in/davidbrown', NULL, DATE_SUB(NOW(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 'Perfect fit for the role, strong analytical skills. Excited to have someone with statistics background.', 5),

(5, '567', 'J000005', 'Eve Davis', 'eve.engineer@email.com', '+1-555-0205', 'I am excited about the DevOps Engineer opportunity at InnovateTech. My experience with AWS, Docker, and Kubernetes aligns perfectly with your requirements. I have successfully built and maintained CI/CD pipelines for multiple projects.', 'Pending', '567_resume.pdf', '567_resume.pdf', '4-6 years', 'InnovateTech', 'DevOps Engineer', 'Bachelor of Computer Engineering', 'https://linkedin.com/in/evedavis', NULL, DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY), NULL, NULL, NULL),

(6, '123', 'J000004', 'Alice Johnson', 'alice.developer@email.com', '+1-555-0201', 'I am also interested in the Data Analyst position. My programming background would be an asset in data analysis work. I have experience with Python data analysis libraries and SQL.', 'Rejected', '123_resume.pdf', '123_resume.pdf', '5-7 years', 'TechCorp Solutions', 'Senior Software Engineer', 'Bachelor of Computer Science', 'https://linkedin.com/in/alicejohnson', 'https://alicejohnson.dev', DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 'Not enough data analysis experience. Better suited for development roles.', 3),

(7, '890', 'J000006', 'Frank Miller', 'frank.marketing@email.com', '+1-555-0206', 'I am applying for the Frontend Developer position at GlobalTech Corp. My experience with React and TypeScript would allow me to contribute to modern web applications. I have built several responsive web applications.', 'Under Review', '890_resume.pdf', '890_resume.pdf', '3-5 years', 'GlobalTech Corp', 'Marketing Specialist', 'Bachelor of Marketing', 'https://linkedin.com/in/frankmiller', 'https://frankmiller.marketing', DATE_SUB(NOW(), INTERVAL 11 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY), 'Good frontend skills, currently in marketing but interested in development. Needs assessment.', 3),

(8, '321', 'J000008', 'Grace Wilson', 'grace.sales@email.com', '+1-555-0207', 'I am interested in the Sales Representative position at StartupCo. My 7 years of sales experience and CRM expertise would help drive revenue for your FinTech platform. I have successfully closed enterprise deals.', 'Pending', '321_resume.pdf', '321_resume.pdf', '6-8 years', 'StartupCo', 'Sales Representative', 'Bachelor of Business Administration', 'https://linkedin.com/in/gracewilson', NULL, DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY), NULL, NULL, NULL),

(9, '654', 'J000009', 'Henry Taylor', 'henry.hr@email.com', '+1-555-0208', 'I am excited about the HR Manager position at MedTech Innovations. My 9 years of HR experience and healthcare industry knowledge make me a perfect fit. I have successfully built HR departments from scratch.', 'Shortlisted', '654_resume.pdf', '654_resume.pdf', '8-10 years', 'MedTech Innovations', 'HR Manager', 'Master of Human Resources', 'https://linkedin.com/in/henrytaylor', NULL, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), 'Excellent HR background, strong healthcare experience. Great cultural fit for our company.', 5),

(10, '987', 'J000010', 'Ivy Anderson', 'ivy.qa@email.com', '+1-555-0209', 'I am applying for the QA Engineer position at GlobalTech Corp. My 5 years of QA experience and automation expertise would help ensure product quality. I have built comprehensive test automation frameworks.', 'Accepted', '987_resume.pdf', '987_resume.pdf', '4-6 years', 'GlobalTech Corp', 'QA Engineer', 'Bachelor of Computer Science', 'https://linkedin.com/in/ivyanderson', NULL, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 'Strong QA background, excellent automation skills. Perfect fit for our testing needs.', 5),

(11, '135', 'J000006', 'Jack Thomas', 'jack.frontend@email.com', '+1-555-0210', 'I am interested in the Frontend Developer position at GlobalTech Corp. My React and TypeScript experience would allow me to contribute immediately. I have built several modern web applications.', 'Pending', '135_resume.pdf', '135_resume.pdf', '2-3 years', 'InnovateTech', 'Frontend Developer', 'Bachelor of Computer Science', 'https://linkedin.com/in/jackthomas', 'https://jackthomas.dev', DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), NULL, NULL, NULL),

(12, '890', 'J000007', 'Frank Miller', 'frank.marketing@email.com', '+1-555-0206', 'I am applying for the Marketing Specialist position at GlobalTech Corp. My 4 years of digital marketing experience and SEO expertise would help grow your brand. I have successfully managed marketing campaigns for tech companies.', 'Accepted', '890_resume.pdf', '890_resume.pdf', '3-5 years', 'GlobalTech Corp', 'Marketing Specialist', 'Bachelor of Marketing', 'https://linkedin.com/in/frankmiller', 'https://frankmiller.marketing', DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 'Strong marketing background, good fit for our digital marketing needs.', 4),

(13, '567', 'J000001', 'Eve Davis', 'eve.engineer@email.com', '+1-555-0205', 'I am interested in the Senior Java Developer position at TechCorp Solutions. My DevOps background includes Java development experience. I would bring infrastructure knowledge to the development team.', 'Rejected', '567_resume.pdf', '567_resume.pdf', '4-6 years', 'InnovateTech', 'DevOps Engineer', 'Bachelor of Computer Engineering', 'https://linkedin.com/in/evedavis', NULL, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 'DevOps background is valuable but lacks deep Java expertise for this senior role.', 2),

(14, '234', 'J000006', 'David Brown', 'david.analyst@email.com', '+1-555-0204', 'I am applying for the Frontend Developer position at GlobalTech Corp. My data analysis experience includes some JavaScript work. I am interested in expanding into frontend development.', 'Under Review', '234_resume.pdf', '234_resume.pdf', '2-3 years', 'TechCorp Solutions', 'Data Analyst', 'Bachelor of Statistics', 'https://linkedin.com/in/davidbrown', NULL, DATE_SUB(NOW(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY), 'Background in data analysis, some JavaScript experience. Needs frontend assessment.', 3),

(15, '456', 'J000007', 'Bob Smith', 'bob.manager@email.com', '+1-555-0202', 'I am interested in the Marketing Specialist position at GlobalTech Corp. My product management experience includes marketing strategy work. I have helped launch products with successful marketing campaigns.', 'Pending', '456_resume.pdf', '456_resume.pdf', '7-10 years', 'InnovateTech', 'Product Manager', 'MBA', 'https://linkedin.com/in/bobsmith', NULL, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), NULL, NULL, NULL);

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;

-- ===============================
-- SUMMARY OF SAMPLE DATA
-- ===============================
-- Companies: 5 records
-- Users: 10 records
-- Jobs: 10 records
-- Applications: 15 records
--
-- Application Status Distribution:
-- - Pending: 5 applications
-- - Under Review: 3 applications
-- - Shortlisted: 2 applications
-- - Accepted: 4 applications
-- - Rejected: 1 application
--
-- Job Categories:
-- - Software Development: 3 jobs
-- - Product Management: 1 job
-- - Design: 1 job
-- - Data Analysis: 1 job
-- - DevOps: 1 job
-- - Marketing: 1 job
-- - Sales: 1 job
-- - HR: 1 job
-- - QA: 1 job
--
-- Salary Ranges: $55k - $160k
-- Experience Levels: 2-10 years
-- Remote Work: 6 jobs offer remote work
-- ===============================
COMMIT;
