-- Sample Data for Arbeit Database
-- Run this script after creating the database and running the application once to create tables

USE arbeit;

-- Insert sample companies
INSERT INTO companies (id, bid, name, email, company_email, company_name, address, city, state, country, zip_code, phone, website, industry, company_size, description, mission, vision, password, role, verified, email_verified, email_verification_token, email_verification_expiry, created_at, updated_at) VALUES
(1, 'B001', 'John Smith', 'john.smith@techcorp.com', 'hr@techcorp.com', 'TechCorp Solutions', '123 Business St', 'San Francisco', 'CA', 'USA', '94105', '+1-555-0101', 'https://techcorp.com', 'Technology', '51-200', 'Leading technology solutions provider', 'To innovate and deliver cutting-edge technology solutions', 'To be the global leader in enterprise software', '$2a$10$encryptedpassword1', 'business', true, true, NULL, NULL, NOW(), NOW()),
(2, 'B002', 'Sarah Johnson', 'sarah.j@innovatetech.com', 'careers@innovatetech.com', 'InnovateTech', '456 Innovation Ave', 'Austin', 'TX', 'USA', '73301', '+1-555-0102', 'https://innovatetech.com', 'Software Development', '11-50', 'Innovative software development company', 'To create innovative software solutions', 'To revolutionize software development', '$2a$10$encryptedpassword2', 'business', true, true, NULL, NULL, NOW(), NOW()),
(3, 'B003', 'Mike Davis', 'mike.d@startupco.com', 'jobs@startupco.com', 'StartupCo', '789 Startup Blvd', 'New York', 'NY', 'USA', '10001', '+1-555-0103', 'https://startupco.com', 'FinTech', '1-10', 'Early-stage FinTech startup', 'To democratize financial services', 'To make financial services accessible to everyone', '$2a$10$encryptedpassword3', 'business', true, true, NULL, NULL, NOW(), NOW());

-- Insert sample users
INSERT INTO users (id, user_id, email, password, first_name, last_name, phone, address, city, state, country, zip_code, role, current_job_title, current_company, experience, skills, education, linkedin_url, github_url, portfolio_url, resume_file_name, resume_file_id, email_verified, email_verification_token, email_verification_expiry, created_at, updated_at) VALUES
(1, '123', 'alice.developer@email.com', '$2a$10$encryptedpassword4', 'Alice', 'Johnson', '+1-555-0201', '123 Main St', 'Seattle', 'WA', 'USA', '98101', 'user', 'Senior Software Engineer', 'TechCorp Solutions', '5-7 years', 'Java,Spring Boot,React,Node.js,Docker', 'Bachelor of Computer Science', 'https://linkedin.com/in/alicejohnson', 'https://github.com/alicejohnson', 'https://alicejohnson.dev', '123_resume.pdf', '123_resume.pdf', true, NULL, NULL, NOW(), NOW()),
(2, '456', 'bob.manager@email.com', '$2a$10$encryptedpassword5', 'Bob', 'Smith', '+1-555-0202', '456 Oak Ave', 'Chicago', 'IL', 'USA', '60601', 'user', 'Product Manager', 'InnovateTech', '7-10 years', 'Product Management,Agile,Scrum,SQL', 'MBA', 'https://linkedin.com/in/bobsmith', NULL, NULL, '456_resume.pdf', '456_resume.pdf', true, NULL, NULL, NOW(), NOW()),
(3, '789', 'carol.designer@email.com', '$2a$10$encryptedpassword6', 'Carol', 'Williams', '+1-555-0203', '789 Pine St', 'Boston', 'MA', 'USA', '02101', 'user', 'UX Designer', 'StartupCo', '3-5 years', 'UI/UX Design,Figma,Adobe XD,User Research', 'Bachelor of Fine Arts', 'https://linkedin.com/in/carolwilliams', NULL, 'https://carolwilliams.design', '789_resume.pdf', '789_resume.pdf', true, NULL, NULL, NOW(), NOW()),
(4, '234', 'david.analyst@email.com', '$2a$10$encryptedpassword7', 'David', 'Brown', '+1-555-0204', '321 Elm St', 'Denver', 'CO', 'USA', '80201', 'user', 'Data Analyst', 'TechCorp Solutions', '2-3 years', 'Python,SQL,Tableau,Excel,Statistics', 'Bachelor of Statistics', 'https://linkedin.com/in/davidbrown', 'https://github.com/davidbrown', NULL, '234_resume.pdf', '234_resume.pdf', true, NULL, NULL, NOW(), NOW()),
(5, '567', 'eve.engineer@email.com', '$2a$10$encryptedpassword8', 'Eve', 'Davis', '+1-555-0205', '654 Maple Ave', 'Portland', 'OR', 'USA', '97201', 'user', 'DevOps Engineer', 'InnovateTech', '4-6 years', 'AWS,Docker,Kubernetes,Jenkins,Python', 'Bachelor of Computer Engineering', 'https://linkedin.com/in/evedavis', 'https://github.com/evedavis', NULL, '567_resume.pdf', '567_resume.pdf', true, NULL, NULL, NOW(), NOW());

-- Insert sample jobs
INSERT INTO jobs (id, job_id, title, company_name, business_name, company_email, bid, location, city, state, country, remote_work, job_type, department, description, requirements, benefits, qualification, skills_required, salary_min, salary_max, salary_currency, hide_salary, screening_questions, hiring_process, application_instructions, status, applicants, posted_date, updated_date, closing_date) VALUES
(1, 'J000001', 'Senior Java Developer', 'TechCorp Solutions', 'TechCorp Solutions', 'hr@techcorp.com', 'B001', 'San Francisco, CA', 'San Francisco', 'CA', 'USA', true, 'Full-time', 'Engineering', 'We are looking for an experienced Java developer to join our team and work on cutting-edge enterprise applications.', '5+ years of Java development experience, Spring Boot proficiency, Microservices experience', 'Health insurance, 401k matching, Flexible work hours, Remote work options', 'Bachelor degree in Computer Science or related field', 'Java,Spring Boot,Microservices,Docker,AWS', 120000.00, 160000.00, 'USD', false, '["What is your experience with Spring Boot?","Describe a challenging project you worked on"]', 'Application Review -> Technical Interview -> Final Interview -> Offer', 'Please include your GitHub profile and a code sample', 'Active', 2, DATE_SUB(NOW(), INTERVAL 7 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY)),
(2, 'J000002', 'Product Manager', 'InnovateTech', 'InnovateTech', 'careers@innovatetech.com', 'B002', 'Austin, TX', 'Austin', 'TX', 'USA', false, 'Full-time', 'Product', 'Join our product team to drive product strategy and development for our innovative software solutions.', '3+ years product management experience, Experience with Agile methodologies, Technical background preferred', 'Competitive salary, Stock options, Health benefits, Learning budget', 'Bachelor degree required, MBA preferred', 'Product Management,Agile,SQL,Analytics', 90000.00, 130000.00, 'USD', false, '["What product have you launched?","How do you prioritize features?"]', 'Resume Review -> Product Case Study -> Leadership Interview -> Offer', 'Include links to products you have launched', 'Active', 1, DATE_SUB(NOW(), INTERVAL 5 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 25 DAY)),
(3, 'J000003', 'UX Designer', 'StartupCo', 'StartupCo', 'jobs@startupco.com', 'B003', 'New York, NY', 'New York', 'NY', 'USA', true, 'Full-time', 'Design', 'We are seeking a talented UX Designer to create intuitive and beautiful user experiences for our FinTech platform.', '3+ years UX design experience, Proficiency in Figma and design systems, Portfolio required', 'Equity package, Health insurance, Flexible hours, Co-working space', 'Bachelor in Design or related field', 'UI/UX Design,Figma,User Research,Design Systems', 70000.00, 100000.00, 'USD', false, '["Show us your design process","What is your favorite design tool?"]', 'Portfolio Review -> Design Challenge -> Team Interview -> Offer', 'Please include your portfolio link and design case studies', 'Active', 0, DATE_SUB(NOW(), INTERVAL 3 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 20 DAY)),
(4, 'J000004', 'Data Analyst', 'TechCorp Solutions', 'TechCorp Solutions', 'hr@techcorp.com', 'B001', 'Remote', 'San Francisco', 'CA', 'USA', true, 'Full-time', 'Analytics', 'Looking for a data analyst to help us make data-driven decisions and create insightful dashboards.', '2+ years data analysis experience, SQL proficiency, Experience with BI tools like Tableau or Power BI', 'Remote work, Learning opportunities, Health benefits, Flexible schedule', 'Bachelor in Mathematics, Statistics, or related field', 'SQL,Python,Tableau,Excel,Statistics', 65000.00, 85000.00, 'USD', false, '["What SQL queries have you written?","Experience with data visualization?"]', 'Technical Assessment -> Data Analysis Interview -> Final Interview', 'Include SQL queries you have written', 'Active', 3, DATE_SUB(NOW(), INTERVAL 10 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 35 DAY)),
(5, 'J000005', 'DevOps Engineer', 'InnovateTech', 'InnovateTech', 'careers@innovatetech.com', 'B002', 'Austin, TX', 'Austin', 'TX', 'USA', false, 'Full-time', 'Engineering', 'We need a DevOps engineer to help us build and maintain our cloud infrastructure and CI/CD pipelines.', '4+ years DevOps/Infrastructure experience, AWS/Azure experience, Container orchestration knowledge', 'Competitive salary, Cloud certifications paid, Flexible work, Learning budget', 'Bachelor in Computer Science or related field', 'AWS,Docker,Kubernetes,Jenkins,Python', 95000.00, 125000.00, 'USD', false, '["What cloud platforms have you worked with?","Experience with Kubernetes?"]', 'Technical Interview -> Infrastructure Design -> Team Fit Interview', 'Include links to infrastructure projects', 'Active', 1, DATE_SUB(NOW(), INTERVAL 8 DAY), NOW(), DATE_ADD(NOW(), INTERVAL 28 DAY));

-- Insert sample applications
INSERT INTO applications (id, user_id, job_id, full_name, email, phone, cover_letter, status, resume_file_name, resume_id, experience, current_company, current_job_title, education, linkedin_url, portfolio_url, applied_date, updated_date, reviewed_date, reviewer_notes, rating) VALUES
(1, '123', 'J000001', 'Alice Johnson', 'alice.developer@email.com', '+1-555-0201', 'I am excited to apply for the Senior Java Developer position at TechCorp Solutions. With 6 years of experience in Java development and Spring Boot, I believe I would be a great fit for your team.', 'Under Review', '123_resume.pdf', '123_resume.pdf', '5-7 years', 'TechCorp Solutions', 'Senior Software Engineer', 'Bachelor of Computer Science', 'https://linkedin.com/in/alicejohnson', 'https://alicejohnson.dev', DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'Strong technical background, good fit for the role', 4),
(2, '456', 'J000002', 'Bob Smith', 'bob.manager@email.com', '+1-555-0202', 'I am interested in the Product Manager position at InnovateTech. My 8 years of product management experience and technical background make me well-suited for this role.', 'Pending', '456_resume.pdf', '456_resume.pdf', '7-10 years', 'InnovateTech', 'Product Manager', 'MBA', 'https://linkedin.com/in/bobsmith', NULL, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), NULL, NULL, NULL),
(3, '789', 'J000003', 'Carol Williams', 'carol.designer@email.com', '+1-555-0203', 'I would love to bring my UX design expertise to StartupCo. My portfolio demonstrates my ability to create user-centered designs that drive business results.', 'Shortlisted', '789_resume.pdf', '789_resume.pdf', '3-5 years', 'StartupCo', 'UX Designer', 'Bachelor of Fine Arts', 'https://linkedin.com/in/carolwilliams', 'https://carolwilliams.design', DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 'Excellent portfolio, strong design skills', 5),
(4, '234', 'J000004', 'David Brown', 'david.analyst@email.com', '+1-555-0204', 'I am applying for the Data Analyst position at TechCorp Solutions. My background in statistics and experience with SQL and Tableau would allow me to contribute immediately.', 'Accepted', '234_resume.pdf', '234_resume.pdf', '2-3 years', 'TechCorp Solutions', 'Data Analyst', 'Bachelor of Statistics', 'https://linkedin.com/in/davidbrown', NULL, DATE_SUB(NOW(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 'Perfect fit for the role, strong analytical skills', 5),
(5, '567', 'J000005', 'Eve Davis', 'eve.engineer@email.com', '+1-555-0205', 'I am excited about the DevOps Engineer opportunity at InnovateTech. My experience with AWS, Docker, and Kubernetes aligns perfectly with your requirements.', 'Pending', '567_resume.pdf', '567_resume.pdf', '4-6 years', 'InnovateTech', 'DevOps Engineer', 'Bachelor of Computer Engineering', 'https://linkedin.com/in/evedavis', NULL, DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY), NULL, NULL, NULL),
(6, '123', 'J000004', 'Alice Johnson', 'alice.developer@email.com', '+1-555-0201', 'I am also interested in the Data Analyst position. My programming background would be an asset in data analysis work.', 'Rejected', '123_resume.pdf', '123_resume.pdf', '5-7 years', 'TechCorp Solutions', 'Senior Software Engineer', 'Bachelor of Computer Science', 'https://linkedin.com/in/alicejohnson', 'https://alicejohnson.dev', DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 'Not enough data analysis experience', 3);

-- Create uploads/resumes directory if it doesn't exist
-- Note: You may need to create this directory manually or the application will create it automatically
